import Vue from 'vue';
import { Tabbar, TabbarItem, Icon, Tab, Tabs, Swipe, SwipeItem } from 'vant';
import { Lazyload } from 'vant';
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Icon);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Lazyload);